server:
  port: $BACKEND_FOR_FRONTENT_SERVER_PORT

database:
  host: $BACKEND_FOR_FRONTEND_DATABASE_HOST
  port: $BACKEND_FOR_FRONTEND_DATABASE_PORT
  user: $BACKEND_FOR_FRONTEND_DATABASE_USER
  password: $BACKEND_FOR_FRONTEND_DATABASE_PASSWORD
  name: $BACKEND_FOR_FRONTEND_DATABASE_NAME
